services:
    sonata.admin.venue:
        class: AppBundle\Admin\VenueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Venue" }
        arguments:
            - ~
            - AppBundle\Entity\Venue
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]